/*
 * OpenWeatherMapAPI.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using OpenWeatherMapAPI.UWP.Controllers;
using OpenWeatherMapAPI.UWP.Http.Client;
using OpenWeatherMapAPI.UWP.Utilities;

namespace OpenWeatherMapAPI.UWP
{
    public partial class OpenWeatherMapAPIClient
    {

        /// <summary>
        /// Singleton access to Weather controller
        /// </summary>
        public WeatherController Weather
        {
            get
            {
                return WeatherController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public OpenWeatherMapAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public OpenWeatherMapAPIClient(string appid)
        {
            Configuration.Appid = appid;
        }
        #endregion
    }
}