/*
 * OpenWeatherMapAPI.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenWeatherMapAPI.UWP;
using OpenWeatherMapAPI.UWP.Utilities;

namespace OpenWeatherMapAPI.UWP.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum LangEnum
    {
        AR, //TODO: Write general description for this method
        BG, //TODO: Write general description for this method
        CA, //TODO: Write general description for this method
        CZ, //TODO: Write general description for this method
        DE, //TODO: Write general description for this method
        EL, //TODO: Write general description for this method
        EN, //TODO: Write general description for this method
        FA, //TODO: Write general description for this method
        FI, //TODO: Write general description for this method
        FR, //TODO: Write general description for this method
        GL, //TODO: Write general description for this method
        HR, //TODO: Write general description for this method
        HU, //TODO: Write general description for this method
        IT, //TODO: Write general description for this method
        JA, //TODO: Write general description for this method
        KR, //TODO: Write general description for this method
        LA, //TODO: Write general description for this method
        LT, //TODO: Write general description for this method
        MK, //TODO: Write general description for this method
        NL, //TODO: Write general description for this method
        PL, //TODO: Write general description for this method
        PT, //TODO: Write general description for this method
        RO, //TODO: Write general description for this method
        RU, //TODO: Write general description for this method
        SE, //TODO: Write general description for this method
        SK, //TODO: Write general description for this method
        SL, //TODO: Write general description for this method
        ES, //TODO: Write general description for this method
        TR, //TODO: Write general description for this method
        UA, //TODO: Write general description for this method
        VI, //TODO: Write general description for this method
        ZH_CN, //TODO: Write general description for this method
        ZH_TW, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type LangEnum
    /// </summary>
    public static class LangEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "ar", "bg", "ca", "cz", "de", "el", "en", "fa", "fi", "fr", "gl", "hr", "hu", "it", "ja", "kr", "la", "lt", "mk", "nl", "pl", "pt", "ro", "ru", "se", "sk", "sl", "es", "tr", "ua", "vi", "zh_cn", "zh_tw" };

        /// <summary>
        /// Converts a LangEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The LangEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(LangEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case LangEnum.AR:
                case LangEnum.BG:
                case LangEnum.CA:
                case LangEnum.CZ:
                case LangEnum.DE:
                case LangEnum.EL:
                case LangEnum.EN:
                case LangEnum.FA:
                case LangEnum.FI:
                case LangEnum.FR:
                case LangEnum.GL:
                case LangEnum.HR:
                case LangEnum.HU:
                case LangEnum.IT:
                case LangEnum.JA:
                case LangEnum.KR:
                case LangEnum.LA:
                case LangEnum.LT:
                case LangEnum.MK:
                case LangEnum.NL:
                case LangEnum.PL:
                case LangEnum.PT:
                case LangEnum.RO:
                case LangEnum.RU:
                case LangEnum.SE:
                case LangEnum.SK:
                case LangEnum.SL:
                case LangEnum.ES:
                case LangEnum.TR:
                case LangEnum.UA:
                case LangEnum.VI:
                case LangEnum.ZH_CN:
                case LangEnum.ZH_TW:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of LangEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of LangEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<LangEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into LangEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed LangEnum value</returns>
        public static LangEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type LangEnum", value));

            return (LangEnum) index;
        }
    }
} 