/*
 * OpenWeatherMapAPI.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenWeatherMapAPI.UWP;
using OpenWeatherMapAPI.UWP.Utilities;


namespace OpenWeatherMapAPI.UWP.Models
{
    public class Snow : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? m3h;

        /// <summary>
        /// Snow volume for the last 3 hours
        /// </summary>
        [JsonProperty("3h")]
        public double? M3h 
        { 
            get 
            {
                return this.m3h; 
            } 
            set 
            {
                this.m3h = value;
                onPropertyChanged("M3h");
            }
        }
    }
} 