/*
 * OpenWeatherMapAPI.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenWeatherMapAPI.UWP;
using OpenWeatherMapAPI.UWP.Utilities;


namespace OpenWeatherMapAPI.UWP.Models
{
    public class SuccessfulResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Coord coord;
        private List<Models.Weather> weather;
        private string mbase;
        private Models.Main main;
        private int? visibility;
        private Models.Wind wind;
        private Models.Clouds clouds;
        private Models.Rain rain;
        private Models.Snow snow;
        private int? dt;
        private Models.Sys sys;
        private int? id;
        private string name;
        private int? cod;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("coord")]
        public Models.Coord Coord 
        { 
            get 
            {
                return this.coord; 
            } 
            set 
            {
                this.coord = value;
                onPropertyChanged("Coord");
            }
        }

        /// <summary>
        /// (more info Weather condition codes)
        /// </summary>
        [JsonProperty("weather")]
        public List<Models.Weather> Weather 
        { 
            get 
            {
                return this.weather; 
            } 
            set 
            {
                this.weather = value;
                onPropertyChanged("Weather");
            }
        }

        /// <summary>
        /// Internal parameter
        /// </summary>
        [JsonProperty("base")]
        public string Base 
        { 
            get 
            {
                return this.mbase; 
            } 
            set 
            {
                this.mbase = value;
                onPropertyChanged("Base");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("main")]
        public Models.Main Main 
        { 
            get 
            {
                return this.main; 
            } 
            set 
            {
                this.main = value;
                onPropertyChanged("Main");
            }
        }

        /// <summary>
        /// Visibility, meter
        /// </summary>
        [JsonProperty("visibility")]
        public int? Visibility 
        { 
            get 
            {
                return this.visibility; 
            } 
            set 
            {
                this.visibility = value;
                onPropertyChanged("Visibility");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("wind")]
        public Models.Wind Wind 
        { 
            get 
            {
                return this.wind; 
            } 
            set 
            {
                this.wind = value;
                onPropertyChanged("Wind");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clouds")]
        public Models.Clouds Clouds 
        { 
            get 
            {
                return this.clouds; 
            } 
            set 
            {
                this.clouds = value;
                onPropertyChanged("Clouds");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("rain")]
        public Models.Rain Rain 
        { 
            get 
            {
                return this.rain; 
            } 
            set 
            {
                this.rain = value;
                onPropertyChanged("Rain");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("snow")]
        public Models.Snow Snow 
        { 
            get 
            {
                return this.snow; 
            } 
            set 
            {
                this.snow = value;
                onPropertyChanged("Snow");
            }
        }

        /// <summary>
        /// Time of data calculation, unix, UTC
        /// </summary>
        [JsonProperty("dt")]
        public int? Dt 
        { 
            get 
            {
                return this.dt; 
            } 
            set 
            {
                this.dt = value;
                onPropertyChanged("Dt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sys")]
        public Models.Sys Sys 
        { 
            get 
            {
                return this.sys; 
            } 
            set 
            {
                this.sys = value;
                onPropertyChanged("Sys");
            }
        }

        /// <summary>
        /// City ID
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Internal parameter
        /// </summary>
        [JsonProperty("cod")]
        public int? Cod 
        { 
            get 
            {
                return this.cod; 
            } 
            set 
            {
                this.cod = value;
                onPropertyChanged("Cod");
            }
        }
    }
} 