/*
 * OpenWeatherMapAPI.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenWeatherMapAPI.UWP;
using OpenWeatherMapAPI.UWP.Utilities;


namespace OpenWeatherMapAPI.UWP.Models
{
    public class Sys : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? type;
        private int? id;
        private double? message;
        private string country;
        private int? sunrise;
        private int? sunset;

        /// <summary>
        /// Internal parameter
        /// </summary>
        [JsonProperty("type")]
        public int? Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// Internal parameter
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Internal parameter
        /// </summary>
        [JsonProperty("message")]
        public double? Message 
        { 
            get 
            {
                return this.message; 
            } 
            set 
            {
                this.message = value;
                onPropertyChanged("Message");
            }
        }

        /// <summary>
        /// Country code (GB, JP etc.)
        /// </summary>
        [JsonProperty("country")]
        public string Country 
        { 
            get 
            {
                return this.country; 
            } 
            set 
            {
                this.country = value;
                onPropertyChanged("Country");
            }
        }

        /// <summary>
        /// Sunrise time, unix, UTC
        /// </summary>
        [JsonProperty("sunrise")]
        public int? Sunrise 
        { 
            get 
            {
                return this.sunrise; 
            } 
            set 
            {
                this.sunrise = value;
                onPropertyChanged("Sunrise");
            }
        }

        /// <summary>
        /// Sunset time, unix, UTC
        /// </summary>
        [JsonProperty("sunset")]
        public int? Sunset 
        { 
            get 
            {
                return this.sunset; 
            } 
            set 
            {
                this.sunset = value;
                onPropertyChanged("Sunset");
            }
        }
    }
} 